data:
  train_csv: data/processed/train.csv
  valid_csv: data/processed/valid.csv

features:
  use_elo: true
  use_rolling: true
  windows: [3, 5, 10]

model:
  type: random_forest
  params:
    n_estimators: 200
    max_depth: null
    random_state: 42

training:
  seed: 42
  experiment_name: plmp_baseline
  output_dir: artifacts


