data:
  train_csv: data/processed/train.csv
  valid_csv: data/processed/valid.csv

features:
  use_elo: true
  use_rolling: true
  windows: [3, 5, 10]

model:
  type: xgboost
  params:
    n_estimators: 300
    max_depth: 4
    learning_rate: 0.08
    subsample: 0.9
    colsample_bytree: 0.9
    objective: multi:softprob
    eval_metric: mlogloss
    num_class: 3
    random_state: 42

training:
  seed: 42
  experiment_name: plmp_xgb
  output_dir: artifacts


